import { RequestValidationError } from '../validation';

type Theme = 'midnight' | 'ocean' | 'sunset' | 'forest';

type OpenGraphImageRequest = {
  title: string;
  subtitle?: string | null;
  brand?: string | null;
  eyebrow?: string | null;
  width?: number;
  height?: number;
  theme?: string | null;
};

type Palette = {
  backgroundStart: string;
  backgroundEnd: string;
  accent: string;
  textPrimary: string;
  textSecondary: string;
};

const THEMES: Record<Theme, Palette> = {
  midnight: {
    backgroundStart: '#0b1220',
    backgroundEnd: '#172554',
    accent: '#38bdf8',
    textPrimary: '#ffffff',
    textSecondary: '#dbeafe'
  },
  ocean: {
    backgroundStart: '#082f49',
    backgroundEnd: '#155e75',
    accent: '#67e8f9',
    textPrimary: '#ecfeff',
    textSecondary: '#cffafe'
  },
  sunset: {
    backgroundStart: '#4c0519',
    backgroundEnd: '#9a3412',
    accent: '#fdba74',
    textPrimary: '#fff7ed',
    textSecondary: '#fed7aa'
  },
  forest: {
    backgroundStart: '#052e16',
    backgroundEnd: '#166534',
    accent: '#86efac',
    textPrimary: '#f0fdf4',
    textSecondary: '#dcfce7'
  }
};

function escapeXml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function normalizeTheme(value: string | null | undefined): Theme {
  if (!value) return 'midnight';

  const normalized = value.trim().toLowerCase();
  if (normalized === 'midnight' || normalized === 'ocean' || normalized === 'sunset' || normalized === 'forest') {
    return normalized;
  }

  throw new RequestValidationError('theme must be one of midnight, ocean, sunset, or forest', {
    field: 'theme'
  });
}

function wrapText(text: string, maxCharsPerLine: number, maxLines: number) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines: string[] = [];
  let current = '';

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length <= maxCharsPerLine) {
      current = next;
      continue;
    }

    if (current) {
      lines.push(current);
      current = word;
    } else {
      lines.push(word.slice(0, maxCharsPerLine));
      current = word.slice(maxCharsPerLine);
    }

    if (lines.length >= maxLines) break;
  }

  if (lines.length < maxLines && current) {
    lines.push(current);
  }

  if (lines.length > maxLines) {
    lines.length = maxLines;
  }

  if (words.length > 0 && lines.length === maxLines) {
    const consumed = lines.join(' ').length;
    if (text.length > consumed) {
      lines[maxLines - 1] = `${lines[maxLines - 1].replace(/[. ]+$/, '')}…`;
    }
  }

  return lines;
}

function textBlock(lines: string[], x: number, startY: number, lineHeight: number, fontSize: number, fill: string, weight = 700) {
  return lines
    .map((line, index) => {
      const y = startY + index * lineHeight;
      return `<text x="${x}" y="${y}" fill="${fill}" font-family="Arial, Helvetica, sans-serif" font-size="${fontSize}" font-weight="${weight}">${escapeXml(line)}</text>`;
    })
    .join('');
}

export function buildOpenGraphImage(request: OpenGraphImageRequest) {
  const title = request.title.trim();
  if (!title) {
    throw new RequestValidationError('title is required', { field: 'title' });
  }

  const subtitle = request.subtitle?.trim() || '';
  const brand = request.brand?.trim() || '';
  const eyebrow = request.eyebrow?.trim() || 'Generated by DataLensAPI';
  const width = Math.max(600, Math.min(request.width ?? 1200, 2000));
  const height = Math.max(315, Math.min(request.height ?? 630, 1200));
  const theme = normalizeTheme(request.theme);
  const palette = THEMES[theme];

  const titleLines = wrapText(title, width >= 1000 ? 26 : 20, 3);
  const subtitleLines = subtitle ? wrapText(subtitle, width >= 1000 ? 40 : 30, 2) : [];
  const titleFontSize = width >= 1000 ? 66 : 52;
  const subtitleFontSize = width >= 1000 ? 28 : 24;
  const brandFontSize = 24;
  const padding = 72;

  const svg = [
    `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${escapeXml(title)}">`,
    '<defs>',
    `<linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">`,
    `<stop offset="0%" stop-color="${palette.backgroundStart}" />`,
    `<stop offset="100%" stop-color="${palette.backgroundEnd}" />`,
    '</linearGradient>',
    '</defs>',
    `<rect width="${width}" height="${height}" rx="32" fill="url(#bg)" />`,
    `<circle cx="${width - 120}" cy="110" r="84" fill="${palette.accent}" fill-opacity="0.16" />`,
    `<circle cx="${width - 220}" cy="${height - 90}" r="120" fill="${palette.accent}" fill-opacity="0.1" />`,
    `<rect x="${padding}" y="56" width="${Math.max(180, Math.min(360, eyebrow.length * 9 + 48))}" height="36" rx="18" fill="${palette.accent}" fill-opacity="0.16" />`,
    `<text x="${padding + 24}" y="80" fill="${palette.textSecondary}" font-family="Arial, Helvetica, sans-serif" font-size="18" font-weight="700" letter-spacing="0.5">${escapeXml(eyebrow)}</text>`,
    textBlock(titleLines, padding, 190, titleFontSize + 10, titleFontSize, palette.textPrimary, 800),
    subtitleLines.length > 0
      ? textBlock(subtitleLines, padding, 190 + titleLines.length * (titleFontSize + 10) + 36, subtitleFontSize + 8, subtitleFontSize, palette.textSecondary, 500)
      : '',
    `<rect x="${padding}" y="${height - 92}" width="${Math.min(width - padding * 2, 320)}" height="8" rx="4" fill="${palette.accent}" />`,
    brand
      ? `<text x="${padding}" y="${height - 44}" fill="${palette.textSecondary}" font-family="Arial, Helvetica, sans-serif" font-size="${brandFontSize}" font-weight="600">${escapeXml(brand)}</text>`
      : ''
  ].join('');

  const closedSvg = `${svg}</svg>`;
  const dataUri = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(closedSvg)}`;

  return {
    status: 'generated' as const,
    title,
    subtitle: subtitle || null,
    brand: brand || null,
    eyebrow,
    theme,
    width,
    height,
    svg: closedSvg,
    dataUri,
    mimeType: 'image/svg+xml',
    filename: 'open-graph-image.svg',
    palette,
    evidence: {
      localSvgGenerated: true,
      titleLineCount: titleLines.length,
      subtitleLineCount: subtitleLines.length,
      themePresetUsed: theme
    }
  };
}
