name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Linter
      run: npm run lint
      continue-on-error: true # Continuing to allow tests to run even if linting fails initially while setting up

    - name: Run Tests
      run: npm run test
      continue-on-error: true

    - name: Build Projects
      run: npm run build
      continue-on-error: true
